from random import randint


def gerador_cpf():
    print("Qual a UF do título?\n")
    print("01 – SP - São Paulo")
    print("02 – MG - Minas Gerais")
    print("03 –  ")
    print("04 – ")
    print("05 – ")
    print("06 – ")
    print("07 – ")
    print("08 – ")
    print("09 – ")
    print("10 - ")
    print("11 - ")
    print("12 – ")
    print("13 – ")
    print("14 – ")
    print("15 – ")
    print("16 – ")
    print("17 – ")
    print("18 – ")
    print("19 – ")
    print("20 - ")
    print("21 - ")
    print("22 – ")
    print("23 – ")
    print("24 – ")
    print("25 – ")
    print("26 – ")
    print("27 – ")
    print("28 – ")